/**
 * Pre-built book style templates.
 * Each template pre-fills tone, length, genre, POV, and structure defaults
 * so the user can get started in one click.
 */

export type BookStyleTemplate = {
  id: string;
  label: string;
  emoji: string;
  tagline: string;
  description: string;
  defaults: {
    genre: string;
    tone: string;
    bookLength: string;
    pov: string;
    formality: string;
    pacing: string;
    sentenceLength: string;
    humor: string;
    vocabulary: string;
    includePreface: boolean;
    includeDedication: boolean;
    includeAcknowledgements: boolean;
    includeEpilogue: boolean;
    writingStyleHint: string;
  };
};

export const BOOK_STYLES: BookStyleTemplate[] = [
  {
    id: "nonfiction-guide",
    label: "How-To Guide",
    emoji: "📘",
    tagline: "Step-by-step instructions on any topic",
    description: "A practical, action-oriented guide that teaches readers a skill or process. Clear, structured, and easy to follow.",
    defaults: {
      genre: "Nonfiction",
      tone: "professional",
      bookLength: "compact",
      pov: "second",
      formality: "neutral",
      pacing: "moderate",
      sentenceLength: "medium",
      humor: "none",
      vocabulary: "intermediate",
      includePreface: true,
      includeDedication: false,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Use numbered steps, clear headings, and practical examples. Each chapter should end with a summary or action checklist.",
    },
  },
  {
    id: "self-help",
    label: "Self-Help Book",
    emoji: "🌱",
    tagline: "Inspire readers to change their lives",
    description: "Motivational and transformational. Combines personal stories, research, and actionable frameworks to help readers grow.",
    defaults: {
      genre: "Self-Help",
      tone: "inspirational",
      bookLength: "medium",
      pov: "second",
      formality: "casual",
      pacing: "moderate",
      sentenceLength: "varied",
      humor: "subtle",
      vocabulary: "simple",
      includePreface: true,
      includeDedication: true,
      includeAcknowledgements: true,
      includeEpilogue: true,
      writingStyleHint: "Open each chapter with a personal story or relatable scenario. Use the 'problem → insight → action' structure. Speak directly to the reader as 'you'.",
    },
  },
  {
    id: "business",
    label: "Business Book",
    emoji: "💼",
    tagline: "Share expertise and build authority",
    description: "A thought leadership book for entrepreneurs, executives, or professionals. Data-driven, strategic, and credibility-building.",
    defaults: {
      genre: "Business",
      tone: "professional",
      bookLength: "medium",
      pov: "third_omni",
      formality: "formal",
      pacing: "moderate",
      sentenceLength: "medium",
      humor: "none",
      vocabulary: "advanced",
      includePreface: true,
      includeDedication: false,
      includeAcknowledgements: true,
      includeEpilogue: false,
      writingStyleHint: "Use case studies, data points, and frameworks. Each chapter should present a core concept, support it with evidence, and end with key takeaways.",
    },
  },
  {
    id: "memoir",
    label: "Memoir",
    emoji: "📖",
    tagline: "Tell your true story",
    description: "A personal narrative drawn from real life. Honest, reflective, and emotionally resonant — your story told your way.",
    defaults: {
      genre: "Memoir",
      tone: "storytelling",
      bookLength: "medium",
      pov: "first",
      formality: "casual",
      pacing: "slow",
      sentenceLength: "varied",
      humor: "subtle",
      vocabulary: "intermediate",
      includePreface: true,
      includeDedication: true,
      includeAcknowledgements: true,
      includeEpilogue: true,
      writingStyleHint: "Write in vivid, sensory detail. Use scene-setting and dialogue. Move between past events and present reflection. Be honest and vulnerable.",
    },
  },
  {
    id: "novel",
    label: "Novel",
    emoji: "✍️",
    tagline: "Write a full-length work of fiction",
    description: "A complete narrative with characters, plot, conflict, and resolution. Full creative freedom across any genre.",
    defaults: {
      genre: "Fiction",
      tone: "storytelling",
      bookLength: "full",
      pov: "third_close",
      formality: "neutral",
      pacing: "moderate",
      sentenceLength: "varied",
      humor: "subtle",
      vocabulary: "intermediate",
      includePreface: false,
      includeDedication: true,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Show, don't tell. Use dialogue, action, and internal monologue. Build tension progressively. Each chapter should end with a hook or unresolved question.",
    },
  },
  {
    id: "childrens",
    label: "Children's Book",
    emoji: "🧸",
    tagline: "Stories for young readers",
    description: "Short, imaginative, and fun. Simple language, vivid characters, and a clear moral or lesson for kids aged 4–12.",
    defaults: {
      genre: "Children's",
      tone: "conversational",
      bookLength: "mini",
      pov: "third_omni",
      formality: "very_casual",
      pacing: "fast",
      sentenceLength: "short",
      humor: "moderate",
      vocabulary: "simple",
      includePreface: false,
      includeDedication: true,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Use short sentences, repetition, and rhyme where appropriate. Include a lovable main character and a clear lesson or moral. Keep chapters very short (1–3 pages each).",
    },
  },
  {
    id: "ebook",
    label: "eBook / Lead Magnet",
    emoji: "📱",
    tagline: "A short, high-value digital download",
    description: "A compact, punchy eBook designed to deliver value fast. Perfect for lead magnets, email opt-ins, or quick-read products.",
    defaults: {
      genre: "Nonfiction",
      tone: "conversational",
      bookLength: "short",
      pov: "second",
      formality: "casual",
      pacing: "fast",
      sentenceLength: "short",
      humor: "subtle",
      vocabulary: "simple",
      includePreface: false,
      includeDedication: false,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Get to the point immediately. Use bullet points, numbered lists, and bold callouts. Each section should be scannable and immediately actionable.",
    },
  },
  {
    id: "workbook",
    label: "Workbook",
    emoji: "📝",
    tagline: "Interactive exercises and prompts",
    description: "A guided workbook with reflection questions, exercises, and fill-in sections. Readers work through it actively, not just read it.",
    defaults: {
      genre: "Self-Help",
      tone: "coaching",
      bookLength: "compact",
      pov: "second",
      formality: "casual",
      pacing: "slow",
      sentenceLength: "short",
      humor: "none",
      vocabulary: "simple",
      includePreface: true,
      includeDedication: false,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Each section should include: a brief explanation, a reflection prompt, and a writing exercise. Use 'You' language throughout. Leave space for the reader to respond.",
    },
  },
  {
    id: "fantasy",
    label: "Fantasy Novel",
    emoji: "🐉",
    tagline: "Epic worlds, magic, and adventure",
    description: "A world-building-heavy fantasy with magic systems, mythical creatures, and an epic quest or conflict at its core.",
    defaults: {
      genre: "Fantasy",
      tone: "storytelling",
      bookLength: "full",
      pov: "third_close",
      formality: "neutral",
      pacing: "moderate",
      sentenceLength: "varied",
      humor: "subtle",
      vocabulary: "advanced",
      includePreface: false,
      includeDedication: true,
      includeAcknowledgements: false,
      includeEpilogue: true,
      writingStyleHint: "Build the world through action and dialogue, not exposition dumps. Introduce magic and lore gradually. Create a clear hero's journey arc with high stakes and a satisfying resolution.",
    },
  },
  {
    id: "thriller",
    label: "Thriller / Mystery",
    emoji: "🔍",
    tagline: "Suspense, twists, and page-turning tension",
    description: "A fast-paced narrative driven by mystery, danger, or a race against time. Every chapter ends with a reason to keep reading.",
    defaults: {
      genre: "Thriller",
      tone: "serious",
      bookLength: "full",
      pov: "third_close",
      formality: "neutral",
      pacing: "fast",
      sentenceLength: "short",
      humor: "none",
      vocabulary: "intermediate",
      includePreface: false,
      includeDedication: true,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Open with a hook in the first paragraph. Use short chapters with cliffhangers. Reveal information slowly. Plant red herrings. Build dread through sensory detail and internal character tension.",
    },
  },
  {
    id: "romance",
    label: "Romance Novel",
    emoji: "💕",
    tagline: "Love stories with emotional depth",
    description: "A character-driven love story with emotional highs and lows, tension, and a satisfying romantic resolution.",
    defaults: {
      genre: "Romance",
      tone: "empathetic",
      bookLength: "medium",
      pov: "third_close",
      formality: "casual",
      pacing: "moderate",
      sentenceLength: "varied",
      humor: "moderate",
      vocabulary: "intermediate",
      includePreface: false,
      includeDedication: true,
      includeAcknowledgements: false,
      includeEpilogue: true,
      writingStyleHint: "Focus on emotional interiority and chemistry between characters. Use tension, misunderstanding, and longing. Dialogue should crackle. The relationship arc is the plot.",
    },
  },
  {
    id: "biography",
    label: "Biography",
    emoji: "🏆",
    tagline: "The story of a remarkable life",
    description: "A narrative account of a real person's life — their struggles, achievements, and legacy. Researched and compelling.",
    defaults: {
      genre: "Biography",
      tone: "journalistic",
      bookLength: "medium",
      pov: "third_omni",
      formality: "formal",
      pacing: "moderate",
      sentenceLength: "medium",
      humor: "none",
      vocabulary: "advanced",
      includePreface: true,
      includeDedication: false,
      includeAcknowledgements: true,
      includeEpilogue: true,
      writingStyleHint: "Blend factual reporting with narrative storytelling. Use chronological structure with thematic chapters. Bring the subject to life through specific scenes and telling details.",
    },
  },
  {
    id: "poetry",
    label: "Poetry Collection",
    emoji: "🌙",
    tagline: "A curated collection of poems",
    description: "A themed poetry collection organized around a central emotion, experience, or idea. Each poem stands alone but contributes to a larger whole.",
    defaults: {
      genre: "Literary Fiction",
      tone: "poetic",
      bookLength: "mini",
      pov: "first",
      formality: "neutral",
      pacing: "slow",
      sentenceLength: "varied",
      humor: "none",
      vocabulary: "advanced",
      includePreface: true,
      includeDedication: true,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Each 'chapter' is a poem or a small cluster of poems on a related theme. Use imagery, metaphor, and line breaks intentionally. The collection should have an emotional arc from beginning to end.",
    },
  },
  {
    id: "academic",
    label: "Academic / Research Book",
    emoji: "🎓",
    tagline: "Scholarly writing for an educated audience",
    description: "A rigorous, well-cited academic work. Structured around a central thesis with evidence-based arguments and formal academic conventions.",
    defaults: {
      genre: "Science",
      tone: "academic",
      bookLength: "extended",
      pov: "third_omni",
      formality: "very_formal",
      pacing: "slow",
      sentenceLength: "long",
      humor: "none",
      vocabulary: "technical",
      includePreface: true,
      includeDedication: false,
      includeAcknowledgements: true,
      includeEpilogue: false,
      writingStyleHint: "State the thesis clearly in the introduction. Each chapter should present a claim, support it with evidence, and address counterarguments. Use formal citation language and avoid colloquialisms.",
    },
  },
  {
    id: "brochure",
    label: "Short Brochure / Report",
    emoji: "📄",
    tagline: "A concise, professional document",
    description: "A short, polished professional document — a white paper, company report, or informational brochure. Scannable and credibility-building.",
    defaults: {
      genre: "Nonfiction",
      tone: "professional",
      bookLength: "mini",
      pov: "third_omni",
      formality: "formal",
      pacing: "fast",
      sentenceLength: "short",
      humor: "none",
      vocabulary: "intermediate",
      includePreface: false,
      includeDedication: false,
      includeAcknowledgements: false,
      includeEpilogue: false,
      writingStyleHint: "Use an executive summary at the start. Keep sections short with clear headers. Use bullet points and data where possible. End with a clear call to action or conclusion.",
    },
  },
];
